<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_message.validator.spam' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidator.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/message-bundle/FOS/MessageBundle/Validator/SpamValidator.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/message-bundle/FOS/MessageBundle/SpamDetection/SpamDetectorInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/message-bundle/FOS/MessageBundle/SpamDetection/NoopSpamDetector.php';

return $this->services['fos_message.validator.spam'] = new \FOS\MessageBundle\Validator\SpamValidator(${($_ = isset($this->services['fos_message.spam_detector']) ? $this->services['fos_message.spam_detector'] : $this->services['fos_message.spam_detector'] = new \FOS\MessageBundle\SpamDetection\NoopSpamDetector()) && false ?: '_'});
