<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/Command/DebugCommand.php';

$this->services['console.command.form_debug'] = $instance = new \Symfony\Component\Form\Command\DebugCommand(${($_ = isset($this->services['form.registry']) ? $this->services['form.registry'] : $this->load('getForm_RegistryService.php')) && false ?: '_'}, array(0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type', 1 => 'AppBundle\\Form', 2 => 'Symfony\\Bridge\\Doctrine\\Form\\Type', 3 => 'FOS\\UserBundle\\Form\\Type', 4 => 'FOS\\MessageBundle\\FormType'), array(0 => 'AppBundle\\Form\\ChampType', 1 => 'AppBundle\\Form\\CvType', 2 => 'AppBundle\\Form\\GroupeType', 3 => 'AppBundle\\Form\\SectionType', 4 => 'AppBundle\\Form\\TemplateEditType', 5 => 'AppBundle\\Form\\TemplateType', 6 => 'AppBundle\\Form\\templateChampType', 7 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType', 8 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType', 9 => 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType', 10 => 'FOS\\UserBundle\\Form\\Type\\UsernameFormType', 11 => 'FOS\\UserBundle\\Form\\Type\\ProfileFormType', 12 => 'FOS\\UserBundle\\Form\\Type\\RegistrationFormType', 13 => 'FOS\\UserBundle\\Form\\Type\\ChangePasswordFormType', 14 => 'FOS\\UserBundle\\Form\\Type\\ResettingFormType', 15 => 'FOS\\MessageBundle\\FormType\\RecipientsType'), array(0 => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\Type\\FormTypeHttpFoundationExtension', 1 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension', 2 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension', 3 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension', 4 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\UploadValidatorExtension', 5 => 'Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension'), array(0 => 'Symfony\\Component\\Form\\Extension\\Validator\\ValidatorTypeGuesser', 1 => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser'));

$instance->setName('debug:form');

return $instance;
