<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSzoqimp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSzoqimp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSzoqimp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSzoqimp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSzoqimp\appProdProjectContainer(array(
    'container.build_hash' => 'Szoqimp',
    'container.build_id' => '141389b7',
    'container.build_time' => 1528906083,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSzoqimp');
