<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYczkuvm\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYczkuvm/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYczkuvm.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYczkuvm\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerYczkuvm\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Yczkuvm',
    'container.build_id' => '45983829',
    'container.build_time' => 1528932631,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYczkuvm');
