<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBo8ufhx\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBo8ufhx/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBo8ufhx.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBo8ufhx\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerBo8ufhx\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Bo8ufhx',
    'container.build_id' => 'c6e73bf4',
    'container.build_time' => 1528973566,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBo8ufhx');
