<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_message.composer' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/message-bundle/FOS/MessageBundle/Composer/ComposerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/message-bundle/FOS/MessageBundle/Composer/Composer.php';

return $this->services['fos_message.composer'] = new \FOS\MessageBundle\Composer\Composer(${($_ = isset($this->services['fos_message.message_manager']) ? $this->services['fos_message.message_manager'] : $this->getFosMessage_MessageManagerService()) && false ?: '_'}, ${($_ = isset($this->services['fos_message.thread_manager']) ? $this->services['fos_message.thread_manager'] : $this->getFosMessage_ThreadManagerService()) && false ?: '_'});
