<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxuwif3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxuwif3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDxuwif3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDxuwif3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDxuwif3\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Dxuwif3',
    'container.build_id' => 'a0f4d935',
    'container.build_time' => 1528906069,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxuwif3');
