<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWblqq9d\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWblqq9d/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWblqq9d.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWblqq9d\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWblqq9d\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wblqq9d',
    'container.build_id' => '647edc63',
    'container.build_time' => 1528973628,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWblqq9d');
